
[logging]
# EnvFilter 문자열 포맷을 따릅니다: 
# <crate_name>=<level>,<another_crate>=<level>
filter = "debug"

[logging.file]
directory = "logs"
filename = "app"

[database]
url = "postgres://user:passwd@localhost:15432/stardust"
pool_size = 1
