[workspace]
members = [
    "stardust-common",
    "stardust-db",
    "stardust-interface",
    "stardust-core",
    "module-user",
    "module-oauth2-server",
    "module-sample",
    "stardust",
    "stardust-app",
]

resolver = "3"
