[package]
name = "stardust-app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.6"
serde = { version = "1.0.228", features = ["derive"] }
stardust-common = { path = "../stardust-common" }
stardust-db = { path = "../stardust-db" }
stardust-inbound = { path = "../stardust-inbound" }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
